-- AlterTable
ALTER TABLE "LocalPurchase" ADD COLUMN IF NOT EXISTS "cashPaid" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LocalPurchase" ADD COLUMN IF NOT EXISTS "onlinePaid" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LocalPurchase" ADD COLUMN IF NOT EXISTS "cashCollected" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LocalPurchase" ADD COLUMN IF NOT EXISTS "changeGiven" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LocalPurchase" ADD COLUMN IF NOT EXISTS "creditAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LocalPurchase" ADD COLUMN IF NOT EXISTS "paymentProofPath" TEXT;
